controllers/StoreManagerController.php
<?php

namespace app\controllers;

use Yii;
use app\behaviors\RoleBehavior;
use app\models\StoreManager;
use app\models\StoreManagerSearch;
use yii\web\Controller;
use app\models\Template;
use app\components\TagsHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * StoreManagerController implements the CRUD actions for StoreManager model.
 */
class StoreManagerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'except' => ['application-form'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Displays a single StoreManager model.
     * 
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        $model = $this->findModel($id);





        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Управление складом #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update', 'id' => $model->id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }



    /**
     * Displays a single StoreManager model.
     * 
     * @return mixed
     */
    public function actionIndex()
    {   
        $request = Yii::$app->request;





        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->render('view', [
                    
            ]);
        }else{
            return $this->render('view', [
                    
            ]);
        }
    }
    /**
     * Displays a single StoreManager model.
     * 
     * @return mixed
     */
    public function actionRemains()
    {   
        $request = Yii::$app->request;


            $storeRemainsSearchModel = new \app\models\StoreRemainsSearch();
        $storeRemainsDataProvider = $storeRemainsSearchModel->search(Yii::$app->request->queryParams);




        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->render('view', [
                    
			'storeRemainsSearchModel'=>$storeRemainsSearchModel,
		'storeRemainsDataProvider'=>$storeRemainsDataProvider,
            ]);
        }else{
            return $this->render('view', [
                    
			'storeRemainsSearchModel'=>$storeRemainsSearchModel,
		'storeRemainsDataProvider'=>$storeRemainsDataProvider,
            ]);
        }
    }
    /**
     * Displays a single StoreManager model.
     * 
     * @return mixed
     */
    public function actionIncome()
    {   
        $request = Yii::$app->request;


            $storeInSearchModel = new \app\models\StoreInSearch();
        $storeInDataProvider = $storeInSearchModel->search(Yii::$app->request->queryParams);




        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->render('view', [
                    
			'storeInSearchModel'=>$storeInSearchModel,
		'storeInDataProvider'=>$storeInDataProvider,
            ]);
        }else{
            return $this->render('view', [
                    
			'storeInSearchModel'=>$storeInSearchModel,
		'storeInDataProvider'=>$storeInDataProvider,
            ]);
        }
    }
    /**
     * Displays a single StoreManager model.
     * 
     * @return mixed
     */
    public function actionOut()
    {   
        $request = Yii::$app->request;


            $storeSalvageSearchModel = new \app\models\StoreSalvageSearch();
        $storeSalvageDataProvider = $storeSalvageSearchModel->search(Yii::$app->request->queryParams);




        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->render('view', [
                    
			'storeSalvageSearchModel'=>$storeSalvageSearchModel,
		'storeSalvageDataProvider'=>$storeSalvageDataProvider,
            ]);
        }else{
            return $this->render('view', [
                    
			'storeSalvageSearchModel'=>$storeSalvageSearchModel,
		'storeSalvageDataProvider'=>$storeSalvageDataProvider,
            ]);
        }
    }
    /**
     * Creates a new StoreManager model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new StoreManager();

        if($request->isGet){
            $model->load(Yii::$app->request->queryParams);
        }


        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить Управление складом",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-store_manager-pjax',
                    'title'=> "Добавить Управление складом",
                    'content'=>'<span class="text-success">Создание Управление складом успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ]; 
        
            }else{           
                return [
                    'title'=> "Добавить Управление складом",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing StoreManager model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * 
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить Управление складом #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-store_manager-pjax',
                    'forceClose' => true,
                ];    
            }else{
                 return [
                    'title'=> "Изменить Управление складом #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
 
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }
    
    

    /**
     * Delete an existing StoreManager model.

views/store-manager/view.php
<?php

use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use app\models\User;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model StoreManager */
?>
<div class="store-manager-view">
 <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="nav-item <?= Yii::$app->controller->action->id == 'index' ? ' active' : '' ?>">
                                <a class="nav-link"  id="home-tab-fill" href="<?= Url::toRoute(['store-manager/index']) ?>" aria-controls="home-fill" aria-selected="true">Сводные данные</a>
                            </li>
                            <li class="nav-item <?= Yii::$app->controller->action->id == 'remains' ? ' active' : '' ?>">
                                <a class="nav-link"  id="home-tab-fill" href="<?= Url::toRoute(['store-manager/remains']) ?>" aria-controls="home-fill" aria-selected="true">Остатки</a>
                            </li>
                            <li class="nav-item <?= Yii::$app->controller->action->id == 'income' ? ' active' : '' ?>">
                                <a class="nav-link"  id="home-tab-fill" href="<?= Url::toRoute(['store-manager/income']) ?>" aria-controls="home-fill" aria-selected="true">Поступления</a>
                            </li>
                            <li class="nav-item <?= Yii::$app->controller->action->id == 'out' ? ' active' : '' ?>">
                                <a class="nav-link"  id="home-tab-fill" href="<?= Url::toRoute(['store-manager/out']) ?>" aria-controls="home-fill" aria-selected="true">Списания</a>
                            </li>
                        </ul>
                        <div class="tab-content pt-1">
                            
                            <div class="tab-pane <?= Yii::$app->controller->action->id == 'index' ? ' active' : '' ?>" id="home-fill" role="tabpanel" aria-labelledby="home-tab-fill">
                                <div class="row">
                                                                        
                        <?php if (Yii::$app->controller->action->id == 'index'):?>
                                <div class="col-md-12">
                                   <?= $this->render("@app/views/store-data/view.php"); ?>
                                </div>

                    <?php endif;?>
                                </div>
                            </div>
                            
                            <div class="tab-pane <?= Yii::$app->controller->action->id == 'remains' ? ' active' : '' ?>" id="home-fill" role="tabpanel" aria-labelledby="home-tab-fill">
                                <div class="row">
                                                                        
                        <?php if (Yii::$app->controller->action->id == 'remains'):?>
                                <div class="col-md-12">
                                   <?= $this->render("@app/views/store-remains/index.php", [
                                        'searchModel' => $storeRemainsSearchModel,
                                        'dataProvider' => $storeRemainsDataProvider,
                                    ]); ?>
                                </div>

                    <?php endif;?>
                                </div>
                            </div>
                            
                            <div class="tab-pane <?= Yii::$app->controller->action->id == 'income' ? ' active' : '' ?>" id="home-fill" role="tabpanel" aria-labelledby="home-tab-fill">
                                <div class="row">
                                                                        
                        <?php if (Yii::$app->controller->action->id == 'income'):?>
                                <div class="col-md-12">
                                   <?= $this->render("@app/views/store-in/index.php", [
                                        'searchModel' => $storeInSearchModel,
                                        'dataProvider' => $storeInDataProvider,
                                    ]); ?>
                                </div>

                    <?php endif;?>
                                </div>
                            </div>
                            
                            <div class="tab-pane <?= Yii::$app->controller->action->id == 'out' ? ' active' : '' ?>" id="home-fill" role="tabpanel" aria-labelledby="home-tab-fill">
                                <div class="row">
                                                                        
                        <?php if (Yii::$app->controller->action->id == 'out'):?>
                                <div class="col-md-12">
                                   <?= $this->render("@app/views/store-salvage/index.php", [
                                        'searchModel' => $storeSalvageSearchModel,
                                        'dataProvider' => $storeSalvageDataProvider,
                                    ]); ?>
                                </div>

                    <?php endif;?>
                                </div>
                            </div>
   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php \yii\bootstrap\Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => [
        'class' => 'modal-big-md',
    ],
    "footer"=>"",// always need it for jquery plugin
]); \yii\bootstrap\Modal::end(); ?>

</div>